
x-default-logging: &default
  {}

x-loki-logging: &loki
  driver: loki
  options:
    loki-url: ${LOKI_URL:-http://localhost:3100/loki/api/v1/push}
    mode: non-blocking
    max-buffer-size: 4m
    loki-retries: "3"

x-log-config: &log-config
  <<: *default

services:
  # Frappe Services
  frappe:
    image: frappe/frappe:${FRAPPE_VERSION:-v15}
    environment:
      DB_HOST: frappedb
      DB_PORT: 3306
      MARIADB_ROOT_PASSWORD: ${FRAPPE_DB_ROOT_PASSWORD:-admin}
      MYSQL_ROOT_PASSWORD: ${FRAPPE_DB_ROOT_PASSWORD:-admin}
      INSTALL_APPS: |
        accreditation-management,https://github.com/logiic-ltd/accreditation-management.git
        qamis-inspection-management,https://github.com/logiic-ltd/qamis-inspection-management.git
    volumes:
      - frappe-sites:/home/frappe/frappe-bench/sites
      - ${FRAPPE_APPS_PATH:-./frappe-apps}:/home/frappe/frappe-bench/apps
    depends_on:
      - frappedb
    logging: *log-config
    restart: unless-stopped

  frappedb:
    image: mariadb:${MARIADB_VERSION:-10.6}
    environment:
      MYSQL_ROOT_PASSWORD: ${FRAPPE_DB_ROOT_PASSWORD:-admin}
      TZ: ${TZ:-UTC}
    volumes:
      - frappe-db:/var/lib/mysql
    logging: *log-config
    restart: unless-stopped
  dhis2:
    image: dhis2/core:${DHIS2_VERSION:-2.41.1}
    environment:
      DHIS2_HOME: /opt/dhis2
      DHIS2_DATABASE_HOST: db
      DHIS2_DATABASE_PORT: 5432
      DHIS2_DATABASE_NAME: ${DHIS2_DB_NAME:-dhis2}
      DHIS2_DATABASE_USERNAME: ${DHIS2_DB_USER:-dhis}
      DHIS2_DATABASE_PASSWORD: ${DHIS2_DB_PASSWORD:-dhis}
      JAVA_OPTS: ${DHIS2_JAVA_OPTS:--Xms2048m -Xmx4096m}
      TZ: ${TZ:-UTC}
    volumes:
      - dhis2-data:/opt/dhis2
      - ../dhis2-config:/opt/dhis2/config:ro
    depends_on:
      - db
    logging: *log-config
    restart: unless-stopped

  db:
    image: postgis/postgis:${POSTGRES_VERSION:-15-3.3}
    environment:
      POSTGRES_DB: ${DHIS2_DB_NAME:-dhis2}
      POSTGRES_USER: ${DHIS2_DB_USER:-dhis}
      POSTGRES_PASSWORD: ${DHIS2_DB_PASSWORD:-dhis}
      TZ: ${TZ:-UTC}
    volumes:
      - db-data:/var/lib/postgresql/data
    logging: *log-config
    restart: unless-stopped

  redis:
    image: redis:${REDIS_VERSION:-7.0-alpine}
    volumes:
      - redis-data:/data
    logging: *log-config
    restart: unless-stopped

  nginx:
    image: nginx:${NGINX_VERSION:-1.25-alpine}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - dhis2
    logging: *log-config
    restart: unless-stopped

  pandasai:
    profiles: ["analytics"]
    image: qamis/pandasai:${PANDASAI_VERSION:-latest}
    environment:
      DHIS2_URL: http://dhis2:8080
      DHIS2_USERNAME: ${DHIS2_USERNAME:-admin}
      DHIS2_PASSWORD: ${DHIS2_PASSWORD:-district}
      TZ: ${TZ:-UTC}
    depends_on:
      - dhis2
    logging: *log-config
    restart: unless-stopped

  prometheus:
    profiles: ["analytics"]
    image: prom/prometheus:${PROMETHEUS_VERSION:-v2.45.0}
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    logging: *log-config
    restart: unless-stopped

  grafana:
    profiles: ["analytics"]
    image: grafana/grafana:${GRAFANA_VERSION:-10.0.3}
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    logging: *log-config
    restart: unless-stopped

volumes:
  dhis2-data:
  db-data:
  redis-data:
  prometheus-data:
  grafana-data:
  frappe-sites:
  frappe-db:
